<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Currencies</name>
   <tag></tag>
   <elementGuidId>be561f03-64f7-47d2-bb4e-8a26071ba008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='settings-collapse']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d36821c7-5ac6-4e0e-a82d-692799966bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>./currencies.php</value>
      <webElementGuid>bdc8bc56-dbbe-4b7e-aa34-f23b43317734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loadeffect link-light  </value>
      <webElementGuid>a019bad7-a016-4b50-a974-b950eac4aa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Currencies</value>
      <webElementGuid>f31cd727-cba7-426c-ad2e-28fab395a1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settings-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small p-0&quot;]/li[4]/a[@class=&quot;loadeffect link-light&quot;]</value>
      <webElementGuid>9c66f92b-0fe2-488d-b1b7-dc95d25f0993</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settings-collapse']/ul/li[4]/a</value>
      <webElementGuid>60535f32-bd36-4211-83e8-f94c13fe5847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Currencies')]</value>
      <webElementGuid>3df8485f-b0eb-4a20-b3e7-a9c1822bf628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, './currencies.php')]</value>
      <webElementGuid>3351942f-ce61-43cf-acf9-8a787c8bb314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>18324dd3-d800-41ff-9388-500169f163a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = './currencies.php' and (text() = 'Currencies' or . = 'Currencies')]</value>
      <webElementGuid>32d12dab-e352-4dab-9bee-bb53b0f6a2c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
