<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Currencies (1)</name>
   <tag></tag>
   <elementGuidId>50a0657b-b30f-409f-b232-e0eef9936ce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='settings-collapse']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3dab7ffd-852f-4365-ad47-ebecba8bcec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>./currencies.php</value>
      <webElementGuid>99dbbea4-fa5f-4f2b-ab56-8d60b1c0f1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loadeffect link-light  </value>
      <webElementGuid>8bd870b0-e94a-404f-92a1-74321d78f362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Currencies</value>
      <webElementGuid>7bca6ada-36ad-45ee-9cab-31585651ea95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settings-collapse&quot;)/ul[@class=&quot;btn-toggle-nav list-unstyled fw-normal pb-1 small p-0&quot;]/li[4]/a[@class=&quot;loadeffect link-light&quot;]</value>
      <webElementGuid>d3dd12d1-26ea-4954-8be3-4c132b72b819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settings-collapse']/ul/li[4]/a</value>
      <webElementGuid>fee5fea9-f222-40ac-9b86-639e7f5758ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Currencies')]</value>
      <webElementGuid>6ea07f6c-61a6-42b6-9135-87bb84c9f18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, './currencies.php')]</value>
      <webElementGuid>3c1fddf0-3b77-40f2-be69-eb15ce1effea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>d2d4b5bd-7302-4315-b6dc-872d98f35f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = './currencies.php' and (text() = 'Currencies' or . = 'Currencies')]</value>
      <webElementGuid>b3054d98-30ac-4f12-a509-9339a9dfd8ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
