<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add</name>
   <tag></tag>
   <elementGuidId>1c78b9ab-6b14-4bcb-98e4-8f4f00a39745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.xcrud-button.xcrud-green.xcrud-action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Add')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>859c0764-d4c5-4387-8c1e-03cc3b005074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>803dc145-37ce-4f57-a612-cfed80ffb6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-task</name>
      <type>Main</type>
      <value>create</value>
      <webElementGuid>844c1348-a946-44b4-81e8-ec6b5b0d36da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcrud-button xcrud-green xcrud-action</value>
      <webElementGuid>346ed4d4-f5f9-4bfa-8087-7ee994a146fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add</value>
      <webElementGuid>407c1030-32af-4f10-a270-eb7d24b325e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;w-100&quot;]/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;xcrud&quot;]/div[@class=&quot;xcrud-container&quot;]/div[@class=&quot;xcrud-ajax&quot;]/div[@class=&quot;xcrud-rightside&quot;]/a[@class=&quot;xcrud-button xcrud-green xcrud-action&quot;]</value>
      <webElementGuid>297b57b4-e529-403f-a182-c1182eed6339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add')])[3]</value>
      <webElementGuid>47980306-7fb5-4c25-8c4a-510e70772c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>c9807cf7-8067-41ba-a1b9-3c5a81fdd5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>54688641-93ae-4150-9736-d22b608af478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = ' Add' or . = ' Add')]</value>
      <webElementGuid>40756c73-5576-4c4c-aeea-7c2aa37ae4f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
