<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>74c37b71-7bd2-48a0-bfbd-4db3090b26f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.xcrud-button.xcrud-purple.xcrud-action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94c2c72c-0ceb-42e9-9ebb-05ff555497a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>f3e331f0-f7fd-4bf8-b874-62d7c9faea7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-task</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>c950f957-7fc1-4b20-8c56-17e4fe4f3d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-after</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>7c789681-badc-4586-8eef-32dac34aa105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcrud-button xcrud-purple xcrud-action</value>
      <webElementGuid>ac37be5a-c8de-4023-981c-9e7c43bd5425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>10e3fcf7-de61-4108-a9c2-486b841429fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;w-100&quot;]/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;xcrud&quot;]/div[@class=&quot;xcrud-container&quot;]/div[@class=&quot;xcrud-ajax&quot;]/div[@class=&quot;xcrud-top-actions&quot;]/a[@class=&quot;xcrud-button xcrud-purple xcrud-action&quot;]</value>
      <webElementGuid>97e06eb1-5c18-42c2-8b88-baa5a93f05ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-primary</name>
      <type>Main</type>
      <value>9441</value>
      <webElementGuid>023da304-3379-4cc2-93f8-13a4c56f1403</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>2113d73b-34b1-4cb1-9725-08bbc9c19505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>9493b421-68cc-409b-866c-e397331c8335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>4d7cc80d-cd34-4602-a02c-1d13524af61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>d029b4e4-b78d-403b-bd80-e1bbb92c5bd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
