<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_bG9jYXRpb25zLmxhdGl0dWRl</name>
   <tag></tag>
   <elementGuidId>8262e04c-b6e2-4572-9823-91dd53b98801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;bG9jYXRpb25zLmxhdGl0dWRl&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='bG9jYXRpb25zLmxhdGl0dWRl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfbdc93a-ce04-45a7-993f-936236b4ab36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcrud-input form-control</value>
      <webElementGuid>49af1bca-2307-4232-b5cb-a3e0e2b57816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8fe1f353-aaf4-4c80-b16b-8e33afecbd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ef0038a-f4e9-4baa-81c4-a45906afaa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bG9jYXRpb25zLmxhdGl0dWRl</value>
      <webElementGuid>06d338f7-f2f4-4f0b-8126-89bb31fac6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>ae621b8f-7d5d-4d60-b199-04bb99df6a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;w-100&quot;]/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;xcrud&quot;]/div[@class=&quot;xcrud-container&quot;]/div[@class=&quot;xcrud-ajax&quot;]/div[@class=&quot;xcrud-view&quot;]/table[@class=&quot;form-horizontal&quot;]/tbody[1]/tr[@class=&quot;mb-1 row&quot;]/td[@class=&quot;col-md-6&quot;]/input[@class=&quot;xcrud-input form-control&quot;]</value>
      <webElementGuid>d84ad8e8-cef7-4e50-bbbb-5678636daf86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='bG9jYXRpb25zLmxhdGl0dWRl']</value>
      <webElementGuid>94892b09-c810-446f-ab7d-391abbf79094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>54b6ffe6-32e7-44a6-b4c1-fca3aa2d620d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bG9jYXRpb25zLmxhdGl0dWRl']</value>
      <webElementGuid>07289666-502b-4731-8c40-363a9835d910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
