<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_bG9jYXRpb25zLmxvbmdpdHVkZQ--</name>
   <tag></tag>
   <elementGuidId>04e3af41-1509-4dde-9d53-3f95805f6b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;bG9jYXRpb25zLmxvbmdpdHVkZQ--&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='bG9jYXRpb25zLmxvbmdpdHVkZQ--']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0924b965-3641-40bf-85c8-89745cceb0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcrud-input form-control</value>
      <webElementGuid>ff0dcea9-2f0d-4e98-a9b0-32be7b9abcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24cc3ba0-d789-4beb-86d2-0f550177679d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a0ca358-7251-4a9a-ac28-310e22627219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bG9jYXRpb25zLmxvbmdpdHVkZQ--</value>
      <webElementGuid>7c786911-abd2-42f9-a58f-d23a1a9114df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>8d3a841e-083b-47ef-9971-79dfe426fb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;w-100&quot;]/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;xcrud&quot;]/div[@class=&quot;xcrud-container&quot;]/div[@class=&quot;xcrud-ajax&quot;]/div[@class=&quot;xcrud-view&quot;]/table[@class=&quot;form-horizontal&quot;]/tbody[1]/tr[@class=&quot;mb-1 row&quot;]/td[@class=&quot;col-md-6&quot;]/input[@class=&quot;xcrud-input form-control&quot;]</value>
      <webElementGuid>78c4dedd-ec9f-4999-901b-8b511a18218f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='bG9jYXRpb25zLmxvbmdpdHVkZQ--']</value>
      <webElementGuid>8529ee1f-4b0c-4141-8a0f-74e7cf680bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>8b701729-1f72-4509-8fd7-cd943a85d9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bG9jYXRpb25zLmxvbmdpdHVkZQ--']</value>
      <webElementGuid>07366408-f788-4f08-b587-d7de14c8f00c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
