<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_bG9jYXRpb25zLmNpdHk-</name>
   <tag></tag>
   <elementGuidId>ec552a96-9465-4c64-a802-b033ea837262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;bG9jYXRpb25zLmNpdHk-&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='bG9jYXRpb25zLmNpdHk-']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>374c7c18-3112-48d7-aefb-279627aacfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcrud-input form-control</value>
      <webElementGuid>e664d76c-abbc-4e89-85b6-8a2fb9281b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>03da64ba-4963-4637-8a09-51bc43f9d451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3be54c07-d824-4333-8b4d-e638408310bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bG9jYXRpb25zLmNpdHk-</value>
      <webElementGuid>7039abfc-d2f1-47ad-a5a0-b47542a5eb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>f42f0b7f-1812-4bfa-aca9-4afc6c8fa99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;w-100&quot;]/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;xcrud&quot;]/div[@class=&quot;xcrud-container&quot;]/div[@class=&quot;xcrud-ajax&quot;]/div[@class=&quot;xcrud-view&quot;]/table[@class=&quot;form-horizontal&quot;]/tbody[1]/tr[@class=&quot;mb-1 row&quot;]/td[@class=&quot;col-md-6&quot;]/input[@class=&quot;xcrud-input form-control&quot;]</value>
      <webElementGuid>73f82d74-9407-4306-88d3-411019c34628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Malaysia</value>
      <webElementGuid>1447e164-b914-4c5b-877b-ac2a4428e474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='bG9jYXRpb25zLmNpdHk-']</value>
      <webElementGuid>edfa41a3-fb31-44ac-bd56-b9dc566eb8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>a38049de-0920-4f2b-a779-b1cf3046f839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bG9jYXRpb25zLmNpdHk-']</value>
      <webElementGuid>cde9d85c-d1bf-452a-b82d-656c32a15195</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
