<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>a3a30d78-58a8-4650-945e-06f593731155</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.xcrud-button.xcrud-purple.xcrud-action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>125a26c0-9768-4a93-8f42-fef56a8f6607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>1cb13a21-1f1a-4af3-890a-3e9a89931036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-task</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>65084224-da44-425c-b845-b947a0c109f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-after</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>11f21acd-ae84-4597-88cf-a5e0ecbdf0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcrud-button xcrud-purple xcrud-action</value>
      <webElementGuid>4f144753-9830-4b8b-80e0-21310e163864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>2af42b6b-e760-45d0-a97d-f265527fb3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;w-100&quot;]/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;xcrud&quot;]/div[@class=&quot;xcrud-container&quot;]/div[@class=&quot;xcrud-ajax&quot;]/div[@class=&quot;xcrud-top-actions&quot;]/a[@class=&quot;xcrud-button xcrud-purple xcrud-action&quot;]</value>
      <webElementGuid>4c7277ea-33f1-42e9-88aa-b8048eaa488d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>55c15cb6-27fc-49cf-afb9-1c4c61383706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>ed8b0993-fb76-413a-af03-56b9af8d81dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>46a21114-5a62-4b8e-9343-8012d3eb8e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>3d07d34e-cc73-4b13-98ef-ecd061947cff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
