<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phrase</name>
   <tag></tag>
   <elementGuidId>4796c23a-8ae7-4e1b-a496-688752b30d87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phrase&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phrase']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2f0bed7-ddc3-4455-9f15-57741ce43418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcrud-searchdata xcrud-search-active xcrud-input-small</value>
      <webElementGuid>ed65bbf4-ae1d-4b59-aa98-3b3739c28027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phrase</value>
      <webElementGuid>85b24f8c-d8ee-4aef-b6e1-ed5f023742c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29eb6654-eaba-4f0e-b7c7-0e70402a76f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fieldtype</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>a10c6879-7462-40ba-be4c-92c4e3c6e1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4d36ca4-629a-4300-897f-4347b2b23ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;w-100&quot;]/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;xcrud&quot;]/div[@class=&quot;xcrud-container&quot;]/div[@class=&quot;xcrud-ajax&quot;]/div[@class=&quot;xcrud-nav&quot;]/span[@class=&quot;xcrud-search&quot;]/span[@class=&quot;xcrud-search&quot;]/input[@class=&quot;xcrud-searchdata xcrud-search-active xcrud-input-small&quot;]</value>
      <webElementGuid>88348d6d-6d97-4b70-83b8-14925530202b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phrase']</value>
      <webElementGuid>3ed0cbb1-5b2e-4640-98a0-27db1f57cba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>bb769702-fe80-492e-b2b6-f8a4cc3d181d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phrase' and @type = 'text']</value>
      <webElementGuid>dab21adb-3384-493e-97ff-366c214d0392</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
